# Unfortunately, we can't use the reusable workflow from NX since we need to use ${{ secrets}}
# We should eject from the reusable workflow and use our own.

name: On Push to Main

on:
  push:
    branches:
      - main

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      main-branch-name: main
      number-of-agents: 3
      environment-variables: 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}'
      parallel-commands-on-agents: |
        npx nx run-many --all --target=build --production
      final-commands: |
        npx nx deploy --production

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 3
